### PR TITLE
Fixes to address changes to the HTML of the result lines

### LINKED ISSUE #12: Changes to the result line cause parsing issues
Due to changes to the CheckUser results line the parsing of IPs and user agents has broken.

### PR DESCRIPTION
**Pull request by Dreamy-Jazz**
Fixes #12

### CODE REVIEW

File: Gadget.js [hunk 1]
```diff
@@ -90,56 +87,68 @@
...
+                    uas[uaText] = uas[uaText] || 0;
+                    uas[uaText] += 1;
                 });
             } else {
-                uas = [ua];
+                uas = {};
+                uas[ua] = 1;
             }
-            var ip = $(this).children('small').children('a').children('bdi').text();
+            console.log($(this).children('.mw-checkuser-indented'));
```
Comment (Ladsgroup) [inline Gadget.js]: Clean these and below ;)

**Review by Ladsgroup — CHANGES_REQUESTED** [review]

File: Gadget.js (hunk 1 above)
Comment (Dreamy-Jazz) [reply Gadget.js]: Done in the next commit. Thanks.

**Review by Ladsgroup — APPROVED** [review]
